### ISSUE TITLE
Finalization issue, telling when an object has been GC'd

### ISSUE THREAD

**Issue by JoshEngebretson** [svaarala/duktape#108]
I have objects with native class instances bound and need to know when the object has been garbage collected and will no longer be referenced in script.

The initial approach has been to use a finalizer.  However, this is problematic as the objects are being rescued outside of the finalizer.  I understand that this can happen, as the guide says "this may happen in special cases even when the object is not rescued by the finalizer".  I am not sure what this means.

I am wondering if there is any reliable way to tell if an object has been GC'd.  (I am using heapptr native side to track the script objects)

Thanks!

**Comment by sva-p** [comment]
The quote relates to multiple execution of a finalizer:

>A finalizer may be called multiple times (this may happen in special cases even when the object is not rescued by the finalizer).

There are some special cases where a finalizer may run twice even when the object was not rescued. This used to happen when an object had been finalized by mark-and-sweep (but not yet wiped) and `duk_destroy_heap()` was called, which then ensured all objects are finalized and ended up calling the finalizer for a second time (IIRC this has been fixed but there may be similar cases).

The fix right now is to make the finalizer capable of detecting it's being executed for the second time (e.g. write a NULL over a native resource pointer or such).

The finalizer is currently the only signal of an object being GC'd - with the catch the Duktape may tell that you twice :)

Fixing the finalizer guarantees to be exact would be nice, I'll add it to the 1.2 release.

**Comment by svaarala** [comment]
The quote relates to multiple execution of a finalizer:

>A finalizer may be called multiple times (this may happen in special cases even when the object is not rescued by the finalizer).

There are some special cases where a finalizer may run twice even when the object was not rescued. This used to happen when an object had been finalized by mark-and-sweep (but not yet wiped) and duk_destroy_heap() was called, which then ensured all objects are finalized and ended up calling the finalizer for a second time (IIRC this has been fixed but there may be similar cases).

The fix right now is to make the finalizer capable of detecting it's being executed for the second time (e.g. write a NULL over a native resource pointer or such).

The finalizer is currently the only signal of an object being GC'd - with the catch the Duktape may tell that you twice :)

Fixing the finalizer guarantees to be exact would be nice, I'll add it to the 1.2 release.

**Comment by JoshEngebretson** [comment]
Hi Sami,

The problem isn't that the finalizer may be called twice, which is pretty easy to catch.  It is that the finalizer is being called while the object is still valid and in use.  So, the native object is gone when it actually shouldn't have been deleted.

I have been catching the 2nd run of the finalizer (which does still happen).  The problem is that the finalizer is run, somehow the object is rescued or shouldn't have had the finalizer called and is still available in script. The object gets accessed after the first finalizer call. 

I know it is the same object because I flagged some properties on it to check and the heapptr matches what was in the first finalizer call.

If I call duk_gc per frame, I cannot seem to trip the issue however this isn't really an option.  If I change the gc to every 5 seconds the problem happens frequently.

My only guess is that the mark/sweep may finalize objects in a closure, but they become reachable on the next pass.. this is just a wild guess though :)

**Comment by JoshEngebretson** [comment]
I should probably also note that the finalizer is a c_function and does not rescue the object

**Comment by svaarala** [comment]
What happens if you run your finalizer as normal, but simply leak the native resource? Do you get a resource leak but no crash?

When you say "the object gets accessed", who accesses it?

**Comment by svaarala** [comment]
Running the finalizer is pretty straightforward in mark-and-sweep, and freeing an object takes two mark-and-sweep passes (when the object has a finalizer, that is):

- Mark-and-sweep pass N marks the object finalizable, and once mark-and-sweep is otherwise finished, finalizers are executed.  The object is still in Duktape heap at this point, but no-one should have a reference to it.

- Assuming the finalizer didn't rescue the object, at this point the object is not reachable through ordinary means. Any C code can still resurrect the object if it uses `duk_push_heapptr()` to create a reference to it.

- Mark-and-sweep pass N+1 detects that the object was finalizable, and if it's still unreachable, the object is freed. If the object is reachable, it's considered rescued.

**Comment by svaarala** [comment]
A finalizer may also be executed (and probably most often is) by the refcount code, without involving mark-and-sweep at all:

* If object refcount becomes zero, the finalizer is executed. For the duration of the finalizer call the refcount is bumped by one to avoid queueing the object again for refcount finalization.

* If the refcount after removing the artificial bump is zero after the finalizer call, the object is freed.

* Unlike mark-and-sweep there should be no delay in this case.

Can you confirm whether your finalizer seems to triggered by refcount (i.e. the object doesn't participate in a reference loop) or mark-and-sweep?

**Comment by JoshEngebretson** [comment]
Ok, fantastic, thanks for all the great details!

The best lead I have now is that somehow: duk_push_heapptr() is being called between finalization and the next pass, so the object is being rescued. 

I can look into whether this is being triggered by refcount or mark-and-sweep.  I'll probably have to detect this case and set a breakpoint on it.

If I leak objects, other than failing the verification checks in our system, there aren't any dangling pointers being accessed by duktape.

Thanks again

**Comment by svaarala** [comment]
It's odd that calling `duk_gc()` fixed the issue for you - the second mark-and-sweep should just free the object but since your code should not "see" that free, it would still be doing a `duk_push_heapptr()` (assuming that is the cause here). Doing that push after the second mark-and-sweep should be unsafe and should most likely cause a crash.

Similarly if the finalizer is executed by refcount code, there should be no time for rescuing (unless the finalizer itself rescues the object) and any `duk_push_heapptr()` for the object afterwards should be unstable.

Let me know if you can pinpoint the problem a bit more :)

**Comment by JoshEngebretson** [comment]
Yes, I let the game run for 30 minutes without issue when calling duk_gc per frame.  I can trip the issue within 15 seconds otherwise.  I was thinking the aggressive gc'ing was just keeping things from being rescued so the finalizer was really final :)

I also don't think it is the heapptr push rescuing the object, as this is only done with a valid heapptr, which is cleared on the first finalizer call

We're crunching for GDC, so I may stick with the aggressive GC for now and come back to figuring out why this seems to either fix or greatly reduce the issue.

**Comment by svaarala** [comment]
One piece of the puzzle I'm missing is what call triggers the issue ("the object gets accessed")?

**Comment by JoshEngebretson** [comment]
Ok, so I just verified that a script object is being finalized, though accessed, by script later.  In the finalizer, I set index 0 of the object to true.  I print index 0 of the object before the call that blows up (which is always the same, not erratic).

"undefined, undefined, undefined, true", the last one is where it has been finalized though should not have been... and if I gc every frame I have not yet seen this behavior.

**Comment by svaarala** [comment]
A possible cause is that the refcount is off by one so that Duktape ends up refcount finalizing the object while it's still reachable. But that should be unstable too, because the object would be freed and removed from the Duktape heap's "heap_allocated" list. Mark-and-sweep would no longer see the object so no-one would be finalizing it for the second time so this doesn't match the symptoms.

Just as a way of pinning down the problem, what happens if you use `DUK_OPT_NO_REFERENCE_COUNTING`?

**Comment by JoshEngebretson** [comment]
On 1.1 (latest download release), with DUK_OPT_NO_REFERENCE_COUNTING set:

[Mon Jan 19 08:15:21 2015] INFO: undefined
[Mon Jan 19 08:15:21 2015] INFO: undefined
[Mon Jan 19 08:15:21 2015] INFO: true

Still having finalize called though accessed (in script) after that finalize call

**Comment by JoshEngebretson** [comment]
Ok, so this kind of seems like a smoking gun, self has not been finalized however a memory of an array it holds has been finalized:

        var sprite = self.sprites[frame];
        // index 0 is set to true once finalized, otherwise undefined
        print(self[0], ":", sprite[0]);

[Mon Jan 19 08:46:28 2015] INFO: undefined:undefined
[Mon Jan 19 08:46:28 2015] INFO: undefined:undefined
[Mon Jan 19 08:46:28 2015] INFO: undefined:true

**Comment by svaarala** [comment]
Hunches on how this could be reproduced in a stripped down test case?

**Comment by JoshEngebretson** [comment]
I filed an Atomic issue to check whether DUK_OPT_NO_VOLUNTARY_GC is still required to avoid the gc issues described here, whether we end up using it to control GC timing or not... 

https://github.com/AtomicGameEngine/AtomicGameEngine/issues/151

I should note that with it disabled these months, objects have been being GC'd properly, with a fair amount of stress on the system.  I do think that https://github.com/svaarala/duktape/issues/109 would be great

**Comment by JoshEngebretson** [comment]
I've been stress testing with the voluntary gc enabled and haven't been able to trip this :+1: 

I think we'll stick with the default of having the voluntary, unless getting some GC pauses... so far, silky smooth!

If you're looking to close out some issues, I think this is now a candidate.

**Comment by JoshEngebretson** [comment]
Unfortunately, I had to disable voluntary GC as I am tripping the issue after some more testing.  Disabling the voluntary GC also seems to smooth out the framerate a bit, so that is desirable.  I will work to get a good minimal repro case when possible

**Comment by svaarala** [comment]
I'll be happy to help with the reproduction if there are any clues what I should be looking for :-)

**Comment by fatcerberus** [comment]
Weird, I've never had a double finalization issue yet, and I would definitely know since it would lead directly to a segfault (double free). :wink:

**Comment by svaarala** [comment]
I'll be happy to help with the reproduction if there are any clues what I should be looking for :-)

**Comment by svaarala** [comment]
@fatcerberus Note that this is not a basic double finalization issue (and there *are* those cases still left); here an object finalizer is called when the object is still in use.

**Comment by fatcerberus** [comment]
Oh.  Ouch!

**Comment by JoshEngebretson** [comment]
It is ok, significantly smoother without the voluntary GC, though I do want to figure this out :)  

I would also like to figure out exactly how to: make dist-src 

using settings https://github.com/svaarala/duktape/blob/master/config/examples/timing_sensitive.yaml 

Crunching and I am sure how to do this is right in front of my face, somewhere :)

**Comment by fatcerberus** [comment]
If I had to guess at the cause of this, I would say there's a refcounting error somewhere, e.g. a corresponding DECREF coming before an INCREF (instead of after) which causes the object to be finalized and then immediately rescued.

**Comment by JoshEngebretson** [comment]
So, when you started developing Duktape, did you think it would be used to control the AI of virtual chickens?

Because it has now been used for this purpose:

![chickens](https://cloud.githubusercontent.com/assets/376203/9457990/dcca9a62-4a9d-11e5-9501-ff4e1f643f42.gif)

Oh, it is also used to make them cluck :)

- Josh

**Comment by fatcerberus** [comment]
> the AI of virtual chickens

AI... artificial intelligence... chickens...

But wait, I thought chickens were stupid? :wink:

**Comment by svaarala** [comment]
That's an awesome application :)

**Comment by svaarala** [comment]
@JoshEngebretson The config YAML files are part of the `duk_config.h` rework (#64) which is still a work-in-progress in 1.3. But what you can do and would do later on is generate a new `duk_config.h` using `genconfig.py`, with specific config options overridden based on option YAML files and/or command line options.

For example:

```
# Options can be defined in YAML files and/or command line entries, applied in order
$ python --metadata config --output duk_config.h \
    --option-file config/examples/timing_sensitive.yaml \
    --option-file my_further_options.yaml \
    -DDUK_USE_FASTINT \
    autodetect-header
```

There's a more verbose explanation here: https://github.com/svaarala/duktape/blob/master/doc/duk-config.rst

**Comment by JoshEngebretson** [comment]
Ok, thanks!  I will give this a shot in a little bit

**Comment by svaarala** [comment]
There isn't all that much in the timing sensitive options, you probably already have the DUK_OPT_xxx variants in your compilation already (DUK_OPT_xxx variants will be removed later on, after 1.3 release, in favor of working with `duk_config.h` and DUK_USE_xxx config options directly, removing one layer of indirection).

But there are a lot more options in performance_sensitive.yaml, so you could e.g. apply performance_sensitive.yaml first, and then timing_sensitive.yaml on top of that. After that you can do additional tweaks. It's not a perfect process but that way you'd automatically inherit new performance related options.

**Comment by svaarala** [comment]
@JoshEngebretson With the fix for #287 in master, now might be a good time to check if you can still reproduce this problem. There are a few torture case failures for finalizers and longjmp handling left (tracked in #314) but they seem quite difficult (if not impossible) to trigger from user code. I'll probably deal with them after the base 1.3.0 release and incorporate the fixes into 1.3.1 if there's something that's actually possible to trigger.

**Comment by JoshEngebretson** [comment]
We're currently crunching here, though this is on my list of things to do.  We're going to leave the voluntary gc off as it really does smooth out frames, though it would be good to know if the behavior persists with #287 in

Until then, Chickens on Android!

![chickens2](https://cloud.githubusercontent.com/assets/376203/9650256/46bbdeea-51b5-11e5-91d4-d5089939113f.gif)

**Comment by svaarala** [comment]
No worries Josh, I know that feeling :) Probably voluntary GC off is the right choice for Atomic anyway, I'm just curious if we found the underlying cause or not - but this can wait :)

**Comment by svaarala** [comment]
There hasn't been activity or a way to reproduce this for a while now so I'm closing this. This can be reopened if there's some way to reproduce or otherwise narrow down the problem.
