### ISSUE TITLE
Error thrown in try/finally with no catch causes internal error

### ISSUE THREAD

**Issue by fatcerberus** [svaarala/duktape#287]
```javascript
try { throw new Error("A pig ate everyone at 8:12"); }
finally { print("*munch*"); }
```

The `finally` runs, but leads to "internal error in bytecode executor longjmp handler".  What's odd is that I can't always reproduce it.  Depending on the surrounding lines, it sometimes works correctly.

**Comment by svaarala** [comment]
Is this in master? I fixed a possibly related issue a while ago: #268.

**Comment by svaarala** [comment]
I can't reproduce this in master with the example code (with assertions enabled and valgrind):

```
$ ./duk test.js
*munch*
Error: A pig ate everyone at 8:12
	global test.js:1 preventsyield
error in executing file test.js
```

**Comment by fatcerberus** [comment]
Hm, I'll see if I can come up with a test case later.

**Comment by fatcerberus** [comment]
Out of curiosity what is `preventsyield`?  I see it on a lot of the `duk` output you've posted, but never figured out what it meant.

**Comment by fatcerberus** [comment]
I still can't manage to reproduce it in isolation, sadly. :(  However, I did compare the debug output between when it works and when it doesn't.

Correct behavior (debug output starting from point of throw):
```
*munch*
[D] duk_js_executor.c:1342 (unknown): -> throw propagated up to entry level, rethrow and exit bytecode executor
[D] duk_api_stack.c:4132 (unknown): fatal error occurred, code 100, message 'main.js' (line: 7)

Error: A pig ate everyone at 8:12
```

When the internal error shows up:
```
*munch*
[D] duk_js_executor.c:1387 (unknown): caught unknown longjmp type 0, treat as internal error
[D] duk_api_stack.c:4132 (unknown): fatal error occurred, code 100, message 'main.js' (line: 66)

Error: internal error in bytecode executor longjmp handler
```

**Comment by svaarala** [comment]
I'll recheck the try-catch diff - it's likely related to that somehow.

If you didn't already do so, could you enable `-DUK_OPT_ASSERTIONS` and see if that turns up anything?

**Comment by fatcerberus** [comment]
Nope, no failed assertions.

**Comment by fatcerberus** [comment]
For what it's worth, the bug happens with the test code above inside of a protected call (`duk_pcall()`).

**Comment by svaarala** [comment]
Ok, so if "munch" gets printed, it's probably ENDFIN which causes the error.

**Comment by svaarala** [comment]
A little bit more digging. Here's the bytecode:

```
; c0 "Error"
; c1 "A pig ate everyone at 8:12"
; c2 "print"
; c3 "*munch*"

00000 000000f3   LDUNDEF    r0
00001 00000033   NOP       
00002 000040b2   TRYCATCH   0x2, r1          ; have_finally
00003 00000073   INVALID    0
00004 8000016e   JUMP       10 (+6)
00005 000000ce   GETVAR     r3, c0
00006 00004102   LDCONST    r4, c1
00007 0080c009   NEW        r3, 1
00008 0000c573   THROW      r3
00009 000004b3   ENDTRY    
00010 004080d2   CSVAR      r3, c2
00011 0000c142   LDCONST    r5, c3
00012 0080c030   CALL       0x0, r3, 1
00013 0000c000   LDREG      r0, r3
00014 00004533   ENDFIN    
00015 000000ef   RETURN     0x3, r0          ; fast_return, have_retval
```

The THROW at PC 8 will eventually call longjmp with "lj_type" set to THROW. This should get passed to the finally part starting at PC 10, in registers R1 (longjmp value, i.e. the error) and R2 (longjmp type). The base register for this (R1) is defined in TRYCATCH at PC 2.

When the finally part is finished, ENDFIN is supposed to rethrow the previous error (here a THROW) at PC 14. To do this it expects to find the value to throw in R1 and its type in R2. For some reason the type in R2 is not correct here which then causes the longjmp handler to fail.

**Comment by svaarala** [comment]
Could you change the following snippet in duk_js_executor.c:

- https://github.com/svaarala/duktape/blob/master/src/duk_js_executor.c#L4130-L4132

To:

```
DUK_D(DUK_DPRINT("ENDFIN: completion value=%!T, type=%!T",
      (duk_tval *) (thr->valstack + cat->idx_base + 0),
      (duk_tval *) (thr->valstack + cat->idx_base + 1)));
```

and get the debug log when the bug is triggered?

**Comment by fatcerberus** [comment]
Okay, I'll try that in a bit.  What's that INVALID opcode in there?

**Comment by svaarala** [comment]
It's the CATCH jump slot for TRYCATCH, but because there's no catch clause it is emitted as INVALID.

**Comment by fatcerberus** [comment]
```
*munch*
[D] duk_js_executor.c:4125 (unknown): ENDFIN: completion value={message/11:"A pig ate everyone at 8:12"/3}, type=0
[D] duk_js_executor.c:1387 (unknown): caught unknown longjmp type 0, treat as internal error
[D] duk_api_stack.c:4132 (unknown): fatal error occurred, code 100, message 'main.js' (line: 68)

Error: internal error in bytecode executor longjmp handler
```

**Comment by svaarala** [comment]
Hum. So the value being thrown is correct but its longjmp type is not.

**Comment by svaarala** [comment]
(Both call and error handling are due for a cleanup and partial rewrite... Hopefully I'll soon have time for it :-)

**Comment by fatcerberus** [comment]
I don't know if it helps at all, but here's the surrounding code for context:

```
	// set up the beta test harness
	TestHarness.initialize();
	
	// show the title screen and start the game!
	if (!DBG_DISABLE_TITLE_CARD) {
		mini.BGM.push('BGM/SpectaclesTheme.ogg');
		ShowLogo('Logos/TitleCard.png', 5.0);
	}
	var session = new TitleScreen('SpectaclesTheme').show();
	
	try { throw new Error("A pig ate everyone at 8:12"); }
	finally { print("*munch*"); }
	
	analogue.getWorld().session = session;
	LucidaClock.initialize();
	MapEngine('Testville.rmp', 60);
```

If I move the try/finally literally *anywhere else* but after `var session = ...`, it works.  In that exact spot the bug happens.

**Comment by svaarala** [comment]
Btw, what happens if you add a dummy catch clause like:

```
    try { throw new Error("A pig ate everyone at 8:12"); }
    catch (e) { throw e; }
    finally { print("*munch*"); }
```

**Comment by fatcerberus** [comment]
What happens is that the bug goes away. :)

**Comment by svaarala** [comment]
Another attempt to corner this problem: do you get the same problem with Duktape 1.2.3 (if that's feasible to test)?

**Comment by svaarala** [comment]
It would also be useful to see what the longjmp type looks when the finally part begins execution (it's wrong at ENDFIN). If you could change the debug level here:

- https://github.com/svaarala/duktape/blob/master/src/duk_js_executor.c#L650-L654

to:

```
DUK_D(DUK_DPRINT("writing catch registers: idx_base=%ld -> %!T, idx_base+1=%ld -> %!T",
	             (long) thr->catchstack[cat_idx].idx_base,
	             (duk_tval *) &thr->heap->lj.value1,
	             (long) (thr->catchstack[cat_idx].idx_base + 1),
	             (duk_tval *) &thr->heap->lj.value2));
```

(Sorry for pestering you with this - I'd test it myself if I could reproduce it :-)

**Comment by fatcerberus** [comment]
No problem, it's probably some bizarre corner case that will never actually come up in the real world (I only found it by screwing around), but I can say from experience that those are usually the hardest bugs to fix. :(

Anyway, output:

```
[D] duk_js_executor.c:654 (unknown): writing catch registers: idx_base=6 -> {message/11:"A pig ate everyone at 8:12"/4}, idx_base+1=7 -> unused
```

**Comment by svaarala** [comment]
Darn, that debug print didn't actually include the relevant value. Could you add this debug print right after the above one:

```
DUK_D(DUK_DPRINT("ljtype is: %d", (int) thr->heap->lj.type);
```

**Comment by svaarala** [comment]
Yeah, the hardest bugs are those context sensitive bugs which are often not caught by even large test sets. For example, the try-finally bug reported earlier was not triggered by any existing test in the Duktape test set, test262, when running Emscripten generated code etc.

**Comment by fatcerberus** [comment]
"ljtype is: 2"

**Comment by svaarala** [comment]
Ok, now we just need to figure where it gets overwritten :-) ... Thanks, I'll do some code reading later tonight and hopefully pinpoint this :)

**Comment by svaarala** [comment]
Oh btw, was it possible to reproduce this in 1.2.3 or do you have code that relies on newer features not present in that version?

**Comment by fatcerberus** [comment]
I should be able to drop in Duktape 1.2.3 to test, yes.  I haven't really made use of the 1.3 additions yet.

**Comment by fatcerberus** [comment]
The bug is indeed reproducible in 1.2.3.

**Comment by svaarala** [comment]
Just to be clear, does this happen every time when the try-finally is in that specific position, or just some of the time?

It seems unlikely this could be an application bug, but just in case, are there any signs of memory unsafe behavior e.g. in the native calls preceding the problem (any crashes etc)?

**Comment by fatcerberus** [comment]
It's 100% reproducible with the try-finally in that exact location.  If I move it elsewhere (either up or down), it works again.

And I haven't noticed any memory corruption or crashes, no.

I'd debug it myself, but MSVC apparently doesn't like the single-file Duktape source, it won't step into Duktape calls and breakpoints set inside Duktape aren't honored.

Would it help if I were to dump the bytecode?  You'd have to tell me how to do that...

**Comment by svaarala** [comment]
Not sure if the bug is bytecode-related but that would surely help.

If you can find a reference to the function somehow and you could use `duk_dump_function()' on it, I can extract the bytecode from the dump.

**Comment by fatcerberus** [comment]
Okay, here's the dump, obtained by calling `duk_dump_function()` and writing out the returned buffer:
https://drive.google.com/open?id=0BxPKLRqQOUSNUEhQYUozWTU5aWc

**Comment by svaarala** [comment]
Here's the relevant bit, doesn't seem much wrong with it.
```
00087 00000033   NOP       
00088 000040b2   TRYCATCH   0x2, r1          ; have_finally
00089 00000073   INVALID    0
00090 8000016e   JUMP       96 (+6)
00091 000800ce   GETVAR     r3, c32
00092 00084102   LDCONST    r4, c33
00093 0080c009   NEW        r3, 1
00094 0000c573   THROW      r3
00095 000004b3   ENDTRY    
00096 004880d2   CSVAR      r3, c34
00097 0008c142   LDCONST    r5, c35
00098 0080c030   CALL       0x0, r3, 1
00099 00004533   ENDFIN
```

Side note: there isn't a bytecode viewer as such but you can get the above by running:

```
$ ./duk --debugger bytecode.duk
```

and then using the debugger web UI: attach, show bytecode.

**Comment by svaarala** [comment]
This seems pretty hard to pin down, I've read through the relevant code paths and can't figure what could be wrong here.

At this point it would be useful to know what R1 and R2 hold at PC 96 (start of finally handling). The debug dump in "handle catch or finally" indicates we had the correct longjmp type there, but it'd be nice to be sure it's still visible at that point (after potential call stack, catch stack, and value stack resizes). I'll suggest a debug print for that shortly.

Do you use threading and/or is there any risk of a "recursive" call into a different Duktape context (but same heap) in TitleScreen() or TitleScreen.show()? A non-allowed recursive Duktape call might have weird side effects, but that doesn't seem likely here.

**Comment by svaarala** [comment]
If you insert this to the top of the bytecode executor before 'ins' is read (https://github.com/svaarala/duktape/blob/master/src/duk_js_executor.c#L2275) we might get useful info:

```
if (act->pc == 96 && fun->nregs >= 3) {
    DUK_D(DUK_DPRINT("R1=%!T R2=%!T", DUK__REGP(1), DUK__REGP(2)));
}
```

**Comment by fatcerberus** [comment]
I'll try the debug print.  minisphere is single-threaded and I only use one context throughout (the one returned by `duk_create_heap()`), so the risk of a recursive call causing clobbering seems low.

**Comment by fatcerberus** [comment]
Okay, I ended up getting back quite a few lines from that, but I assume this is the correct one as it mentions the thrown Error object:

```
[D] duk_js_executor.c:2270 (unknown): R1={message/11:"A pig ate everyone at 8:12"/4} R2=0
```

**Comment by fatcerberus** [comment]
Incidentally, I've never seen a %!T printf format specifier before, what exactly is it?

**Comment by svaarala** [comment]
Duktape has a custom debug formatter so that you can easily format duk_tvals (`%!T`), duk_hobjects (`%!O`) etc.

**Comment by svaarala** [comment]
Thanks for that debug print - so, R2 is zero on entry to finally so it's not related to what's done in the finally block. Do you get the same error if the finally part is empty (no print)?

**Comment by fatcerberus** [comment]
Yes, empty finally has the same issue.

**Comment by svaarala** [comment]
The rest of the bug huntery would be to figure out (1) does duk__handle_catch_or_finally() manage to write the longjmp type to `thr->valstack + cat->idx_base + 1` and (2) at what point after that (probably inside duk__handle_catch_or_finally()) it gets assigned a zero.

I'll work up a branch with the necessary debug prints and provide a snapshot tomorrow.

**Comment by fatcerberus** [comment]
I always uncover the weirdest bugs don't I? :stuck_out_tongue_closed_eyes:

**Comment by fatcerberus** [comment]
So, I went ahead and did this:

```c
	DUK_DDD(DUK_DDDPRINT("writing catch registers: idx_base=%ld -> %!T, idx_base+1=%ld -> %!T",
	                     (long) thr->catchstack[cat_idx].idx_base,
	                     (duk_tval *) &thr->heap->lj.value1,
	                     (long) (thr->catchstack[cat_idx].idx_base + 1),
	                     (duk_tval *) &thr->heap->lj.value2));
	
	DUK_D(DUK_DPRINT("ljtype %u", thr->heap->lj.type));

	tv1 = thr->valstack + thr->catchstack[cat_idx].idx_base;
	DUK_TVAL_SET_TVAL(&tv_tmp, tv1);
	DUK_TVAL_SET_TVAL(tv1, &thr->heap->lj.value1);
	DUK_TVAL_INCREF(thr, tv1);
	DUK_TVAL_DECREF(thr, &tv_tmp);  /* side effects */

	DUK_D(DUK_DPRINT("ljtype %u", thr->heap->lj.type));

	tv1 = thr->valstack + thr->catchstack[cat_idx].idx_base + 1;
	DUK_TVAL_SET_TVAL(&tv_tmp, tv1);
	DUK_TVAL_SET_NUMBER(tv1, (duk_double_t) thr->heap->lj.type);  /* XXX: set int */
	DUK_ASSERT(!DUK_TVAL_IS_HEAP_ALLOCATED(tv1));   /* no need to incref */
	DUK_TVAL_DECREF(thr, &tv_tmp);  /* side effects */

	DUK_D(DUK_DPRINT("ljtype %u", thr->heap->lj.type));
```

Output was:
```
[D] duk_js_executor.c:656 (unknown): ljtype 2
[D] duk_js_executor.c:664 (unknown): ljtype 0
[D] duk_js_executor.c:672 (unknown): ljtype 0
```

So by the time the longjmp type is written to R2, it's already been reset to zero.  I'm wondering if it's those "side effects" mentioned on the DECREF calls...

**Comment by fatcerberus** [comment]
You know, in hindsight I'm really surprised that the invalid longjmp didn't trigger an assert...

**Comment by fatcerberus** [comment]
I did it!  Here's a minimal test case to reproduce the bug:

```
function Food() {
	this.getEaten = function() { print("The pig ate all the food, and then..."); };
}
Duktape.fin(Food.prototype, function() {})
new Food().getEaten();
try { throw new Error("A pig ate everyone at 8:12"); }
finally { print("*munch*"); }
```

It appears to be an interaction between the try-catch handler and finalization.  That TitleScreen class doesn't have a finalizer, but it creates native objects which do.

**Comment by svaarala** [comment]
Awesome, now I'll be able to work on this much more easily :-)

**Comment by svaarala** [comment]
The side effects won't write to value stack as such; what "side effects" mean there is that an arbitrary amount of other code may run, which may cause reallocation of value stack, catch stack, call stack, etc, so any pointers may become invalid.

But in this case I think what happens is that the longjmp type gets changed because a DECREF triggers finalization, and the call handling related to finalization will overwrite the (global) longjmp state. I'll check all the longjmp related DECREF sites; probably this isn't an issue elsewhere. If so, the simple fix is to make a local copy of the longjmp type before operating with side effects.

**Comment by svaarala** [comment]
Here's the minimal fix branch ('ll go through the other call sites before merging):

- https://github.com/svaarala/duktape/compare/fix-finally-internal-error-gh287

And here's a snapshot if you want to try it out:

- http://duktape.org/snapshots/duktape-1.2.99-20150822074244-v1.2.0-368-g4fd4be4.tar.xz

It seems to fix the regression test case anyway :)

**Comment by svaarala** [comment]
The preconditions for triggering this are pretty interesting:

- There must be a preceding expression that leaves a temporary value in either of the TRYCATCH opcode slots, with that temporary value having a finalizer.
- That temporary value must be the only reference around so that the finalizer gets triggered.
- There must be a try-finally with no catch part
- An error must be thrown from the try part

It might actually be better to scrub (and decref) the TRYCATCH registers on entering the try part instead of letting them keep their values until needed; this way the finalizer would already run in TRYCATCH and the rest of TRYCATCH handling could rely on the slots having a known value (undefined for example).

**Comment by svaarala** [comment]
It might actually be cleanest to store/restore longjmp state explicitly for finalizer calls. I'll give a try and see what that would look like.

**Comment by fatcerberus** [comment]
It's not quite so much of an edge case as it seems at first, though: If ANY object is finalized as a result of the DECREF (not just the temporary value itself), the bug is triggered.

**Comment by svaarala** [comment]
But there are only two DECREFs in the critical path where a finalizer run matters - for the two previous values of TRYCATCH registers. The finalizer must be in either value or some other value reachable (only) through these values. Other finalizers can't be triggered as far as I can see.

**Comment by fatcerberus** [comment]
Yeah, I think that's what happened with that `new TitleScreen().Show()` call above: the TitleScreen object itself doesn't have a finalizer, but it created objects implemented in C that do.  Once the TitleScreen object was collected, those objects became unreachable too.

**Comment by fatcerberus** [comment]
If longjmp state saving doesn't work out, another alternative might be to postpone finalization on refzero with some sort of finalization queue.  That's probably not ideal for footprint, though.

**Comment by svaarala** [comment]
I think the fix I posted above should be enough, at least it fixed the testcase you provided. But it'd be nice to have a less error prone solution.

There actually is a finalization queue already: the refzero queue. Objects are placed there and the queue is pumped until it becomes empty (new objects can be added when finalizing earlier ones). Current refcount macros always empty the queue on refzero, but I have a branch for 1.4 to add macros that don't do that. These will be useful in improving call handling performance but would also be useful here because it's easier to control where side effects can happen.

Anyway, I don't want to do these changes in this branch :)

**Comment by fatcerberus** [comment]
Okay, I tried out the snapshot, it indeed fixed the testcase, as well as the original context where I first discovered the bug (after the TitleScreen call).  Thanks!

**Comment by fatcerberus** [comment]
Incidentally, why *does* finalization clobber the longjmp state?  Are finalizers run in a protected environment?  Or is it just that an ecmascript function is called at all?

**Comment by svaarala** [comment]
Call handling will clean up the longjmp type on its way in the success path at least, so that's probably what's causing it.

**Comment by svaarala** [comment]
Just to summarize, a proper safe fix would be either to:

- Scrub the TRYCATCH registers (only the regbase+1 if regbase+0 contains a string) on TRYCATCH opcode so that there can be no side effects when writing to them later. This also triggers finalization of whatever temporary values were in those registers.
- Change the value stack regbase+0 and regbase+1 writing to use a DECREF-without-refzero primitive to avoid side effects when writing to the value stack; then pump the refzero queue explicitly. Macro support for this is needed anyway for e.g. call handling performance work, so this would just implement the bare minimum to get started on that track.

**Comment by fatcerberus** [comment]
That second one sounds like an easy way to create a memory leak if done carelessly.

**Comment by svaarala** [comment]
It wouldn't be a memory leak as such: the refcounts are managed correctly and the objects are placed in the refzero queue (to be processed, i.e. finalized and freed). If that "pump refzero queue" call is missing, an error occurs or whatever, the very next time refzero queue is emptied things will return to normal with no leak.

**Comment by svaarala** [comment]
Anyway, doing multiple DECREFs with no refzero in-between will be necessary to improve performance. Running the refzero implies sometimes running finalizers which have basically all possible side effects. For example, all pointers that may have changed due to a resize must be looked up again explicitly which is tedious and decreases performance.

For instance in call handling, it will probably be possible to unwind all the callstack entries without triggering side effects, and then only at the very end do the refzero processing.

**Comment by fatcerberus** [comment]
More stable pointers are always a good thing. :-)

**Comment by svaarala** [comment]
I'm actually quite looking forward to spending a bit of time on call handling and that refcount thing. Using the approach described above will mean smaller footprint, better performance, and easier to read and less error prone code. What's not to like :-)

**Comment by svaarala** [comment]
If the TRYCATCH registers are set to undefined during handling of TRYCATCH it has two benefits: (1) finalizers are executed earlier than otherwise which is always preferable, and (2) there's actually no need to DECREF a previous value in longjmp handling because we know that the previous value in that register slot is a primitive value (undefined) which eliminates a DECREF and any related side effects.

So I'll implement that as the minimal fix here, and add that to 1.2.4 release too.

**Comment by svaarala** [comment]
Good news is that the refzero finalizer torture test reproduces this issue automatically, along with the other cases I speculated about above.

**Comment by svaarala** [comment]
Running the whole test set with refzero finalizer torture (it takes a while), the news is pretty good: there are only a few failing test cases and they all fall into the pattern identified above (side effects when setting up TRYCATCH idx_base + 0 and idx_base + 1 registers). The test cases are:

- test-bug-throw-in-catch
- test-dev-yield-from-constructor
- test-dev-yield-from-eval

These may cause issues without the torture test (as @fatcerberus's example demonstrates) but the cases are quite hard to hit in ordinary cases, and may require e.g. an Error object to have a finalizer, or other uncommon requirements.

The fix for this issue should fix these cases too, of course, with the torture test enabled.

**Comment by svaarala** [comment]
@JoshEngebretson The finalizer + TRYCATCH handling related issues in this issue might explain the finalizer behavior in #108. Let's see if your issue (if you can reproduce it) gets fixed once this is addressed.

**Comment by svaarala** [comment]
There are quite many places in error handling where side effects may pop up so it would be best to rework error handling so that there would be no heap-wide state involved when handling errors Specifically, `heap->lj` is shared and if a DECREF causes a finalizer run, it gets clobbered. `lj.type` is one obvious thing but also `lj.value1` and/or `lj.value2` may become clobbered. This is rather a big change so I'll look into this for Duktape 1.4 when reworking call handling (error handling is convenient to rework at the same time). 

However, a very simple fix would be to disable processing pending refzero list entries while error handling is in process (`heap->lj.type != DUK_LJ_TYPE_UNKNOWN`). This effectively protects against recursive error handling, but care must be taken that all setjmp handlers eventually set `heap->lj.type` to DUK_LJ_TYPE_UNKNOWN); they should already. This workaround seems to fix the abovementioned cases and would be easy to backport into Duktape 1.2.4 too. I'll try this out to see if there are any harmful side effects of this.

**Comment by svaarala** [comment]
@fatcerberus Here's a fix branch incorporating the "prevent finalizers during error handling" fix, TRYCATCH "scrubbing", and DECREF_NORZ macros (decref with refzero queueing but no automatic freeing a.k.a. side effects). It'd be interesting to hear if this fixes your issues.

@JoshEngebretson If these "finalizer side effects during error handling" cases were the root cause of your GC and finalizer issues, this branch might be worth testing to see if it affects the occasional issue you had (in case you can reproduce it).

Fix branch is here:

- https://github.com/svaarala/duktape/compare/fix-error-handling-side-effects-gh287

Snapshot here:

- http://duktape.org/snapshots/duktape-1.2.99-20150828154213-v1.2.0-431-g5ec81de.tar.xz

Ignore compiler warnings, I'll fix them before merge.

**Comment by fatcerberus** [comment]
Yes, the try-finally bugs seem to be gone with this snapshot.  Out of curiosity, what does the number in the middle of the WIP versions represent?

```
v1.2.0-431-g5ec81de
```

For example, in this case 431.

**Comment by fatcerberus** [comment]
Haha, for some reason I thought the fix for this was already in master, boy was I in for a rude awakening when I pulled the latest build.  I went through so many snapshots and branches that I guess I forgot this wasn't actually properly fixed yet. :)

**Comment by svaarala** [comment]
The number comes directly from `git describe` and is the number of commits since the tag identified (`v1.2.0` in this case, i.e. 431 commits since that).

There's a couple of things to do before this branch can be merged:

- I'll implement a similar torture test for mark-and-sweep finalizers.
- I'll need to disable finalizers during mark-and-sweep too when setjmp/longjmp handling is active (this is missing in the snapshot above and may actually be related to Josh's problem because "no voluntary gc" flag fixed it).
- I'd like to hear a bit more results from stress tests from applications using finalizers (if possible) because the change is not trivial.

But, I'll push those missing mark-and-sweep changes soon and then let this branch sit for a day or so in case there's a chance for further feedback or test results.

**Comment by svaarala** [comment]
The mark-and-sweep torture test can't be similar to the refcount one because finalizable objects are placed on a finalization based on them actually having a finalizer (refcount refzero free algorithm sees all objects). But, the torture test can make one dummy call per mark-and-sweep, and also ensure callstack and catchstack are resized.

**Comment by svaarala** [comment]
The TRYCATCH scrub fix is now in master, which fixes the finally issue and should actually fix any other issues related to the TRYCATCH catch registers. Unlike discussed above, this should also work with a try-catch-finally, even when the error value being thrown has a finalizer. The finalizer is not an issue because thrown errors don't become unreachable during error handling so the finalizers will never run during the critical sections. This fix is easy to cherry pick into 1.2.4.

I'm working on a separate change to prevent finalizers anywhere when longjmp handling is active (a simple and sufficient proxy for that is `thr->heap->lj.type` being different from zero). That change would have prevented this issue, and any other finalizer side effects during longjmp handling. I don't know what concrete issues like that can exist in practice, but it's safest to exclude them entirely.

**Comment by fatcerberus** [comment]
Looked at the diff for the final fix, this is beautifully elegant:
```
duk_to_undefined(ctx, bc);
duk_to_undefined(ctx, bc + 1);
```

A huge improvement over the decref/incref juggling required before.

**Comment by fatcerberus** [comment]
As for setting a finalizer on `Object.prototype`... that's completely diabolical and I should try that now. ;)

**Comment by svaarala** [comment]
Unless there's a concrete issue left here, I opened #314 to deal with the other torture test. These cases may not be possible to trigger in practice (at least without adding a finalizer to e.g. `Object.prototype`), but it's still best to ensure torture test results are clean.
